<a href="https://colab.research.google.com/github/RaniellyPatricia/previsao-conversao-leads-cursos/blob/main/notebooks/01_entendimento_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 01 - Entendimento inicial da base de leads

Este notebook faz parte do MVP 1 do projeto de Produto de Dados para Análise e Previsão de Conversão de Leads em Cursos.

O objetivo desta etapa é importar a base de dados no Google Colab e realizar uma primeira verificação estrutural, analisando:

- quantidade de linhas e colunas;
- nomes das colunas;
- tipos de dados;
- valores nulos;
- primeiras linhas da base;
- variável de conversão.

Essa etapa é importante para entender se a base está adequada para as próximas fases de limpeza, análise exploratória e construção do dashboard.

In [3]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
files.upload = files.upload()

Saving Leads_X_Education_traduzido_PTBR.csv to Leads_X_Education_traduzido_PTBR (1).csv

In [4]:
df = pd.read_csv("Leads_X_Education_traduzido_PTBR.csv")

In [5]:
df.head()

,ID do Prospect,Número do Lead,Origem do Lead,Fonte do Lead,Não Enviar E-mail,Não Ligar,Convertido,Total de Visitas,Tempo Total no Site,Visualizações de Página por Visita,...,Receber Atualizações Sobre Conteúdo de Marketing Digital,Perfil do Lead,Cidade,Índice de Atividade Assimétrica,Índice de Perfil Assimétrico,Pontuação de Atividade Assimétrica,Pontuação de Perfil Assimétrico,Concordo em Pagar o Valor por Cheque,Cópia Gratuita de Mastering The Interview,Última Atividade Relevante
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Chat Olark,Não,Não,0,0.0,0,0.0,...,Não,Não informado,Não informado,02.Médio,02.Médio,15.0,15.0,Não,Não,Modificado
1,2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Busca Orgânica,Não,Não,0,5.0,674,2.5,...,Não,Não informado,Não informado,02.Médio,02.Médio,15.0,15.0,Não,Não,E-mail Aberto
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Envio por Landing Page,Tráfego Direto,Não,Não,1,2.0,1532,2.0,...,Não,Lead Potencial,Mumbai,02.Médio,01.Alto,14.0,20.0,Não,Sim,E-mail Aberto
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Envio por Landing Page,Tráfego Direto,Não,Não,0,1.0,305,1.0,...,Não,Não informado,Mumbai,02.Médio,01.Alto,13.0,17.0,Não,Não,Modificado
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Envio por Landing Page,Google,Não,Não,1,2.0,1428,1.0,...,Não,Não informado,Mumbai,02.Médio,01.Alto,15.0,18.0,Não,Não,Modificado

## Dimensão da base

Nesta etapa, foi verificada a quantidade de linhas e colunas da base. Essa informação ajuda a entender o tamanho do conjunto de dados analisado.

In [6]:
linhas, colunas = df.shape

print(f"A base possui {linhas} linhas e {colunas} colunas.")

A base possui 9240 linhas e 37 colunas.

## Nomes das colunas

Nesta etapa, foram listadas todas as colunas disponíveis na base para entender quais informações existem sobre os leads.

In [7]:
for coluna in df.columns:
    print(coluna)

ID do Prospect
Número do Lead
Origem do Lead
Fonte do Lead
Não Enviar E-mail
Não Ligar
Convertido
Total de Visitas
Tempo Total no Site
Visualizações de Página por Visita
Última Atividade
País
Especialização
Como Soube da X Education
Ocupação Atual
O que Mais Importa na Escolha do Curso
Busca
Revista
Artigo de Jornal
Fóruns da X Education
Jornal
Anúncio Digital
Por Recomendações
Receber Mais Atualizações Sobre Nossos Cursos
Tags
Qualidade do Lead
Atualizar Sobre Conteúdo de Supply Chain
Receber Atualizações Sobre Conteúdo de Marketing Digital
Perfil do Lead
Cidade
Índice de Atividade Assimétrica
Índice de Perfil Assimétrico
Pontuação de Atividade Assimétrica
Pontuação de Perfil Assimétrico
Concordo em Pagar o Valor por Cheque
Cópia Gratuita de Mastering The Interview
Última Atividade Relevante

## Tipos de dados

Nesta etapa, foi verificado o tipo de dado de cada coluna e a quantidade de valores preenchidos. Essa análise ajuda a identificar colunas numéricas, categóricas e possíveis valores ausentes.

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9240 entries, 0 to 9239
Data columns (total 37 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   ID do Prospect                                            9240 non-null   object
 1   Número do Lead                                            9240 non-null   int64
 2   Origem do Lead                                            9240 non-null   object
 3   Fonte do Lead                                             9204 non-null   object
 4   Não Enviar E-mail                                         9240 non-null   object
 5   Não Ligar                                                 9240 non-null   object
 6   Convertido                                                9240 non-null   int64
 7   Total de Visitas                                          9103 non-null   float64
 8   Tempo Total no Site                                       9240 non-null   int64
 9   Visualizações de Página por Visita                        9103 non-null   float64
 10  Última Atividade                                          9137 non-null   object
 11  País                                                      6779 non-null   object
 12  Especialização                                            7802 non-null   object
 13  Como Soube da X Education                                 7033 non-null   object
 14  Ocupação Atual                                            6550 non-null   object
 15  O que Mais Importa na Escolha do Curso                    6531 non-null   object
 16  Busca                                                     9240 non-null   object
 17  Revista                                                   9240 non-null   object
 18  Artigo de Jornal                                          9240 non-null   object
 19  Fóruns da X Education                                     9240 non-null   object
 20  Jornal                                                    9240 non-null   object
 21  Anúncio Digital                                           9240 non-null   object
 22  Por Recomendações                                         9240 non-null   object
 23  Receber Mais Atualizações Sobre Nossos Cursos             9240 non-null   object
 24  Tags                                                      5887 non-null   object
 25  Qualidade do Lead                                         4473 non-null   object
 26  Atualizar Sobre Conteúdo de Supply Chain                  9240 non-null   object
 27  Receber Atualizações Sobre Conteúdo de Marketing Digital  9240 non-null   object
 28  Perfil do Lead                                            6531 non-null   object
 29  Cidade                                                    7820 non-null   object
 30  Índice de Atividade Assimétrica                           5022 non-null   object
 31  Índice de Perfil Assimétrico                              5022 non-null   object
 32  Pontuação de Atividade Assimétrica                        5022 non-null   float64
 33  Pontuação de Perfil Assimétrico                           5022 non-null   float64
 34  Concordo em Pagar o Valor por Cheque                      9240 non-null   object
 35  Cópia Gratuita de Mastering The Interview                 9240 non-null   object
 36  Última Atividade Relevante                                9240 non-null   object
dtypes: float64(4), int64(3), object(30)
memory usage: 2.6+ MB

## Diagnóstico de valores nulos

Nesta etapa, foi criada uma tabela para identificar a quantidade e o percentual de valores nulos em cada coluna.

In [9]:
tipos_dados = pd.DataFrame({
    "coluna": df.columns,
    "tipo_dado": df.dtypes.values,
    "valores_preenchidos": df.notnull().sum().values,
    "valores_nulos": df.isnull().sum().values,
    "percentual_nulos": (df.isnull().mean().values * 100).round(2)
})

tipos_dados.sort_values(by="percentual_nulos", ascending=False)

,coluna,tipo_dado,valores_preenchidos,valores_nulos,percentual_nulos
25,Qualidade do Lead,object,4473,4767,51.59
31,Índice de Perfil Assimétrico,object,5022,4218,45.65
32,Pontuação de Atividade Assimétrica,float64,5022,4218,45.65
30,Índice de Atividade Assimétrica,object,5022,4218,45.65
33,Pontuação de Perfil Assimétrico,float64,5022,4218,45.65
24,Tags,object,5887,3353,36.29
15,O que Mais Importa na Escolha do Curso,object,6531,2709,29.32
28,Perfil do Lead,object,6531,2709,29.32
14,Ocupação Atual,object,6550,2690,29.11
11,País,object,6779,2461,26.63
13,Como Soube da X Education,object,7033,2207,23.89
12,Especialização,object,7802,1438,15.56
29,Cidade,object,7820,1420,15.37
9,Visualizações de Página por Visita,float64,9103,137,1.48
7,Total de Visitas,float64,9103,137,1.48
10,Última Atividade,object,9137,103,1.11
3,Fonte do Lead,object,9204,36,0.39
4,Não Enviar E-mail,object,9240,0,0.00
2,Origem do Lead,object,9240,0,0.00
1,Número do Lead,int64,9240,0,0.00
0,ID do Prospect,object,9240,0,0.00
20,Jornal,object,9240,0,0.00
19,Fóruns da X Education,object,9240,0,0.00
18,Artigo de Jornal,object,9240,0,0.00
17,Revista,object,9240,0,0.00
16,Busca,object,9240,0,0.00
8,Tempo Total no Site,int64,9240,0,0.00
5,Não Ligar,object,9240,0,0.00
6,Convertido,int64,9240,0,0.00
27,Receber Atualizações Sobre Conteúdo de Marketi...,object,9240,0,0.00
26,Atualizar Sobre Conteúdo de Supply Chain,object,9240,0,0.00
22,Por Recomendações,object,9240,0,0.00
23,Receber Mais Atualizações Sobre Nossos Cursos,object,9240,0,0.00
21,Anúncio Digital,object,9240,0,0.00
34,Concordo em Pagar o Valor por Cheque,object,9240,0,0.00
35,Cópia Gratuita de Mastering The Interview,object,9240,0,0.00
36,Última Atividade Relevante,object,9240,0,0.00

## Verificação de linhas duplicadas

Nesta etapa, foi verificado se existem registros duplicados na base, pois duplicidades poderiam distorcer indicadores como total de leads e taxa de conversão.

In [10]:
duplicadas = df.duplicated().sum()

print(f"A base possui {duplicadas} linhas duplicadas.")

A base possui 0 linhas duplicadas.

## Análise da variável de conversão

Nesta etapa, foi analisada a variável `Convertido`, que indica se o lead realizou conversão ou não.

Nesta base:

- `1` representa lead convertido;
- `0` representa lead não convertido.

In [11]:
conversao = df["Convertido"].value_counts().reset_index()
conversao.columns = ["status_conversao", "quantidade"]

conversao["percentual"] = (
    df["Convertido"].value_counts(normalize=True).values * 100
).round(2)

conversao

   status_conversao  quantidade  percentual
0                 0        5679       61.46
1                 1        3561       38.54

In [12]:
taxa_conversao = df["Convertido"].mean() * 100

print(f"Taxa geral de conversão: {taxa_conversao:.2f}%")

Taxa geral de conversão: 38.54%

## Separação entre colunas numéricas e categóricas

Nesta etapa, as colunas foram separadas conforme o tipo de dado. Essa separação ajuda a definir quais análises fazem sentido para cada variável.

As colunas numéricas serão usadas para análises de médias, distribuição e comportamento dos leads. Já as colunas categóricas serão usadas para contagens, agrupamentos e comparação de conversão entre grupos.

In [13]:
colunas_numericas = df.select_dtypes(include=["int64", "float64"]).columns.tolist()
colunas_categoricas = df.select_dtypes(include=["object"]).columns.tolist()

print("Colunas numéricas:")
print(colunas_numericas)

print("\nColunas categóricas:")
print(colunas_categoricas)

Colunas numéricas:
['Número do Lead', 'Convertido', 'Total de Visitas', 'Tempo Total no Site', 'Visualizações de Página por Visita', 'Pontuação de Atividade Assimétrica', 'Pontuação de Perfil Assimétrico']

Colunas categóricas:
['ID do Prospect', 'Origem do Lead', 'Fonte do Lead', 'Não Enviar E-mail', 'Não Ligar', 'Última Atividade', 'País', 'Especialização', 'Como Soube da X Education', 'Ocupação Atual', 'O que Mais Importa na Escolha do Curso', 'Busca', 'Revista', 'Artigo de Jornal', 'Fóruns da X Education', 'Jornal', 'Anúncio Digital', 'Por Recomendações', 'Receber Mais Atualizações Sobre Nossos Cursos', 'Tags', 'Qualidade do Lead', 'Atualizar Sobre Conteúdo de Supply Chain', 'Receber Atualizações Sobre Conteúdo de Marketing Digital', 'Perfil do Lead', 'Cidade', 'Índice de Atividade Assimétrica', 'Índice de Perfil Assimétrico', 'Concordo em Pagar o Valor por Cheque', 'Cópia Gratuita de Mastering The Interview', 'Última Atividade Relevante']

## Análise das categorias mais frequentes

Nesta etapa, foram analisados os valores mais frequentes das colunas categóricas. O objetivo é entender quais categorias aparecem com mais frequência na base e identificar colunas úteis para o dashboard do MVP 1.

In [14]:
for coluna in colunas_categoricas:
    print(f"\nColuna: {coluna}")
    print(df[coluna].value_counts().head(10))

Coluna: ID do Prospect
ID do Prospect
571b5c8e-a5b2-4d57-8574-f2ffb06fdeff    1
7927b2df-8bba-4d29-b9a2-b6e0beafe620    1
2a272436-5132-4136-86fa-dcc88c88f482    1
8cc8c611-a219-4f35-ad23-fdfd2656bd8a    1
0cc2df48-7cf4-4e39-9de9-19797f9b38cc    1
3256f628-e534-4826-9d63-4a8b88782852    1
2058ef08-2858-443e-a01f-a9237db2f5ce    1
9fae7df4-169d-489b-afe4-0f3d752542ed    1
c55de92b-9295-40e1-90e8-a628c349c292    1
68e53bdc-b66d-48ef-8592-973a8a65377e    1
Name: count, dtype: int64

Coluna: Origem do Lead
Origem do Lead
Envio por Landing Page            4886
API                               3580
Formulário de Cadastro de Lead     718
Importação de Lead                  55
Formulário Rápido de Cadastro        1
Name: count, dtype: int64

Coluna: Fonte do Lead
Fonte do Lead
Google                 2873
Tráfego Direto         2543
Chat Olark             1755
Busca Orgânica         1154
Referência              534
Site Welingak           142
Sites de Referência     125
Facebook                 55
Bing                      6
Clique para Ligar         4
Name: count, dtype: int64

Coluna: Não Enviar E-mail
Não Enviar E-mail
Não    8506
Sim     734
Name: count, dtype: int64

Coluna: Não Ligar
Não Ligar
Não    9238
Sim       2
Name: count, dtype: int64

Coluna: Última Atividade
Última Atividade
E-mail Aberto                 3437
SMS Enviado                   2745
Conversa no Chat Olark         973
Página Visitada no Site        640
Convertido em Lead             428
E-mail Rejeitado               326
Link do E-mail Clicado         267
Formulário Enviado no Site     116
Inalcançável                    93
Descadastrado                   61
Name: count, dtype: int64

Coluna: País
País
Índia                     6492
Estados Unidos              69
Emirados Árabes Unidos      53
Singapura                   24
Arábia Saudita              21
Reino Unido                 15
Austrália                   13
Catar                       10
Hong Kong                    7
Bahrein                      7
Name: count, dtype: int64

Coluna: Especialização
Especialização
Não informado                      1942
Gestão Financeira                   976
Gestão de Recursos Humanos          848
Gestão de Marketing                 838
Gestão de Operações                 503
Administração de Empresas           403
Gestão de Projetos de TI            366
Gestão da Cadeia de Suprimentos     349
Bancos, Investimentos e Seguros     338
Mídia e Publicidade                 203
Name: count, dtype: int64

Coluna: Como Soube da X Education
Como Soube da X Education
Não informado          5043
Busca Online            808
Boca a Boca             348
Aluno da SomeSchool     310
Outro                   186
Múltiplas Fontes        152
Anúncios                 70
Mídias Sociais           67
E-mail                   26
SMS                      23
Name: count, dtype: int64

Coluna: Ocupação Atual
Ocupação Atual
Desempregado              5600
Profissional Empregado     706
Estudante                  210
Outro                       16
Dona de Casa                10
Empresário                   8
Name: count, dtype: int64

Coluna: O que Mais Importa na Escolha do Curso
O que Mais Importa na Escolha do Curso
Melhores Perspectivas de Carreira    6528
Flexibilidade e Conveniência            2
Outro                                   1
Name: count, dtype: int64

Coluna: Busca
Busca
Não    9226
Sim      14
Name: count, dtype: int64

Coluna: Revista
Revista
Não    9240
Name: count, dtype: int64

Coluna: Artigo de Jornal
Artigo de Jornal
Não    9238
Sim       2
Name: count, dtype: int64

Coluna: Fóruns da X Education
Fóruns da X Education
Não    9239
Sim       1
Name: count, dtype: int64

Coluna: Jornal
Jornal
Não    9239
Sim       1
Name: count, dtype: int64

Coluna: Anúncio Digital
Anúncio Digital
Não    9236
Sim       4
Name: count, dtype: int64

Coluna: Por Recomendações
Por Recomendações
Não    9233
Sim       7
Name: count, dtype: int64

Coluna: Receber Mais Atualizações Sobre Nossos Cursos
Receber Mais Atualizações Sobre Nossos Cursos
Não    9240
Name: count, dtype: int64

Coluna: Tags
Tags
Retornará após ler o e-mail             2072
Chamando                                1203
Interessado em outros cursos             513
Já é estudante                           465
Fechado pela Horizzon                    358
Telefone desligado                       240
Ocupado                                  186
Perdido para EINS                        175
Não fará educação adicional              145
Interessado em MBA em tempo integral     117
Name: count, dtype: int64

Coluna: Qualidade do Lead
Qualidade do Lead
Talvez              1560
Incerto             1092
Alta Relevância      637
Muito Baixa          601
Baixa Relevância     583
Name: count, dtype: int64

Coluna: Atualizar Sobre Conteúdo de Supply Chain
Atualizar Sobre Conteúdo de Supply Chain
Não    9240
Name: count, dtype: int64

Coluna: Receber Atualizações Sobre Conteúdo de Marketing Digital
Receber Atualizações Sobre Conteúdo de Marketing Digital
Não    9240
Name: count, dtype: int64

Coluna: Perfil do Lead
Perfil do Lead
Não informado                        4146
Lead Potencial                       1613
Outros Leads                          487
Aluno da SomeSchool                   241
Estudante Lateral                      24
Estudante de Dupla Especialização      20
Name: count, dtype: int64

Coluna: Cidade
Cidade
Mumbai                           3222
Não informado                    2249
Thane e Arredores                 752
Outras Cidades                    686
Outras Cidades de Maharashtra     457
Outras Cidades Metropolitanas     380
Cidades Tier II                    74
Name: count, dtype: int64

Coluna: Índice de Atividade Assimétrica
Índice de Atividade Assimétrica
02.Médio    3839
01.Alto      821
03.Baixo     362
Name: count, dtype: int64

Coluna: Índice de Perfil Assimétrico
Índice de Perfil Assimétrico
02.Médio    2788
01.Alto     2203
03.Baixo      31
Name: count, dtype: int64

Coluna: Concordo em Pagar o Valor por Cheque
Concordo em Pagar o Valor por Cheque
Não    9240
Name: count, dtype: int64

Coluna: Cópia Gratuita de Mastering The Interview
Cópia Gratuita de Mastering The Interview
Não    6352
Sim    2888
Name: count, dtype: int64

Coluna: Última Atividade Relevante
Última Atividade Relevante
Modificado                    3407
E-mail Aberto                 2827
SMS Enviado                   2172
Página Visitada no Site        318
Conversa no Chat Olark         183
Link do E-mail Clicado         173
E-mail Rejeitado                60
Descadastrado                   47
Inalcançável                    32
Teve Conversa por Telefone      14
Name: count, dtype: int64

## Interpretação inicial das categorias

A análise das categorias mais frequentes mostrou que algumas variáveis possuem maior potencial para o MVP 1, principalmente aquelas relacionadas à origem, fonte, atividade, perfil e qualidade do lead.

As colunas `Origem do Lead`, `Fonte do Lead`, `Última Atividade`, `Última Atividade Relevante`, `Especialização`, `Ocupação Atual`, `Qualidade do Lead` e `Perfil do Lead` foram consideradas relevantes para as próximas análises, pois ajudam a entender de onde os leads vêm, como interagem com a empresa e quais perfis têm maior potencial de conversão.

Também foram identificadas colunas com baixo valor analítico para o dashboard inicial, principalmente aquelas com apenas uma categoria ou com predominância quase total de uma única resposta, como `Revista`, `Receber Mais Atualizações Sobre Nossos Cursos`, `Atualizar Sobre Conteúdo de Supply Chain`, `Receber Atualizações Sobre Conteúdo de Marketing Digital` e `Concordo em Pagar o Valor por Cheque`.

A coluna `ID do Prospect` será mantida apenas como identificador, pois possui um valor único para cada lead e não é adequada para gráficos ou análises agregadas.

As colunas com muitos registros como `Não informado` serão analisadas com cuidado nas próximas etapas, pois podem indicar ausência de preenchimento ou limitação na coleta dos dados.

## Conclusão da etapa

Nesta etapa, foi realizada a importação e o diagnóstico inicial da base de leads no Google Colab.

A base possui 9.240 linhas e 37 colunas. Não foram identificadas linhas duplicadas. A variável principal de conversão é `Convertido`, em que `1` representa lead convertido e `0` representa lead não convertido.

A taxa geral de conversão identificada foi de 38,54%, indicando que aproximadamente 4 em cada 10 leads da base realizaram conversão.

Também foram analisados os tipos de dados, valores nulos, colunas numéricas, colunas categóricas e principais categorias presentes na base.

As próximas etapas do MVP 1 serão limpeza, padronização e análise exploratória para construção dos indicadores que irão alimentar o dashboard de conversão.